export const shoeImageMap: Record<string, any> = {


    'ASICS GT Runner blue.png': require('../../assets/image/Shoes/ASICS GT Runner blue.png'),
    'ASICS GT Runner green.png': require('../../assets/image/Shoes/ASICS GT Runner green.png'),
    'ASICS GT Runner yellow.png': require('../../assets/image/Shoes/ASICS GT Runner yellow.png'),
    'ASICS Gel Kayano green.png': require('../../assets/image/Shoes/ASICS Gel Kayano green.png'),
    'ASICS Gel Kayano grey.png': require('../../assets/image/Shoes/ASICS Gel Kayano grey.png'),
    'ASICS Gel Kayano nevy blue.png': require('../../assets/image/Shoes/ASICS Gel Kayano nevy blue.png'),
    'ASICS Gel Nimbus black.png': require('../../assets/image/Shoes/ASICS Gel Nimbus black.png'),
    'ASICS Gel Nimbus white.png': require('../../assets/image/Shoes/ASICS Gel Nimbus white.png'),
    'ASICS Novablast black.png': require('../../assets/image/Shoes/ASICS Novablast black.png'),
    'ASICS Novablast green.png': require('../../assets/image/Shoes/ASICS Novablast green.png'),
    'ASICS Novablast orange.png': require('../../assets/image/Shoes/ASICS Novablast orange.png'),
    'ASICS Roadhawk black.png': require('../../assets/image/Shoes/ASICS Roadhawk black.png'),
    'ASICS Roadhawk grey.png': require('../../assets/image/Shoes/ASICS Roadhawk grey.png'),
    'ASICS Roadhawk white.png': require('../../assets/image/Shoes/ASICS Roadhawk white.png'),
    'Adidas Adizero Speed grey.png': require('../../assets/image/Shoes/Adidas Adizero Speed grey.png'),
    'Adidas Adizero Speed red.png': require('../../assets/image/Shoes/Adidas Adizero Speed red.png'),
    'Adidas Adizero Speed white.png': require('../../assets/image/Shoes/Adidas Adizero Speed white.png'),
    'Adidas Duramo Flex grey.png': require('../../assets/image/Shoes/Adidas Duramo Flex grey.png'),
    'Adidas Duramo Flex white.png': require('../../assets/image/Shoes/Adidas Duramo Flex white.png'),
    'Adidas Runfalcon Pro ligth green.png': require('../../assets/image/Shoes/Adidas Runfalcon Pro ligth green.png'),
    'Adidas Runfalcon Pro nevy blue.png': require('../../assets/image/Shoes/Adidas Runfalcon Pro nevy blue.png'),
    'Adidas Supernova Rise grey.png': require('../../assets/image/Shoes/Adidas Supernova Rise grey.png'),
    'Adidas Supernova Rise ligth green.png': require('../../assets/image/Shoes/Adidas Supernova Rise ligth green.png'),
    'Adidas Supernova Rise ligth white.png': require('../../assets/image/Shoes/Adidas Supernova Rise ligth white.png'),
    'Adidas Ultraboost Prime black.png': require('../../assets/image/Shoes/Adidas Ultraboost Prime black.png'),
    'Adidas Ultraboost Prime red.png': require('../../assets/image/Shoes/Adidas Ultraboost Prime red.png'),
    'New Balance 1080 Fresh black.png': require('../../assets/image/Shoes/New Balance 1080 Fresh black.png'),
    'New Balance 1080 Fresh white.png': require('../../assets/image/Shoes/New Balance 1080 Fresh white.png'),
    'New Balance 550 Street crime.png': require('../../assets/image/Shoes/New Balance 550 Street crime.png'),
    'New Balance 550 Street white.png': require('../../assets/image/Shoes/New Balance 550 Street white.png'),
    'New Balance 574 Core blue.png': require('../../assets/image/Shoes/New Balance 574 Core blue.png'),
    'New Balance 574 Core crim.png': require('../../assets/image/Shoes/New Balance 574 Core crim.png'),
    'New Balance 574 Core pink.png': require('../../assets/image/Shoes/New Balance 574 Core pink.png'),
    'New Balance 9060 Pro green.png': require('../../assets/image/Shoes/New Balance 9060 Pro green.png'),
    'New Balance 9060 Pro grey.png': require('../../assets/image/Shoes/New Balance 9060 Pro grey.png'),
    'New Balance 9060 Pro white.png': require('../../assets/image/Shoes/New Balance 9060 Pro white.png'),
    'New Balance FuelCell Rebel blue.png': require('../../assets/image/Shoes/New Balance FuelCell Rebel blue.png'),
    'New Balance FuelCell Rebel orange.png': require('../../assets/image/Shoes/New Balance FuelCell Rebel orange.png'),
    'New Balance FuelCell Rebel red.png': require('../../assets/image/Shoes/New Balance FuelCell Rebel red.png'),
    'Nike Air Max Alpha black.png': require('../../assets/image/Shoes/Nike Air Max Alpha black.png'),
    'Nike Air Max Alpha ligth blue.png': require('../../assets/image/Shoes/Nike Air Max Alpha ligth blue.png'),
    'Nike Downshifter X black.png': require('../../assets/image/Shoes/Nike Downshifter X black.png'),
    'Nike Downshifter X blue.png': require('../../assets/image/Shoes/Nike Downshifter X blue.png'),
    'Nike Pegasus Lite crim.png': require('../../assets/image/Shoes/Nike Pegasus Lite crim.png'),
    'Nike Pegasus Lite pink.png': require('../../assets/image/Shoes/Nike Pegasus Lite pink.png'),
    'Nike Revolution Pro black.png': require('../../assets/image/Shoes/Nike Revolution Pro black.png'),
    'Nike Revolution Pro green.png': require('../../assets/image/Shoes/Nike Revolution Pro green.png'),
    'Nike Revolution Pro red.png': require('../../assets/image/Shoes/Nike Revolution Pro red.png'),
    'Nike Zoom Runner X green.png': require('../../assets/image/Shoes/Nike Zoom Runner X green.png'),
    'Puma Deviate Elite light green.png': require('../../assets/image/Shoes/Puma Deviate Elite light green.png'),
    'Puma Deviate Elite orange.png': require('../../assets/image/Shoes/Puma Deviate Elite orange.png'),
    'Puma Deviate Elite white.png': require('../../assets/image/Shoes/Puma Deviate Elite white.png'),
    'Puma Flex Runner blue.png': require('../../assets/image/Shoes/Puma Flex Runner blue.png'),
    'Puma Flex Runner grey.png': require('../../assets/image/Shoes/Puma Flex Runner grey.png'),
    'Puma Flex Runner ligth blue.png': require('../../assets/image/Shoes/Puma Flex Runner ligth blue.png'),
    'Puma Flyer Lite ligth blue.png': require('../../assets/image/Shoes/Puma Flyer Lite ligth blue.png'),
    'Puma RS-X Style grey.png': require('../../assets/image/Shoes/Puma RS-X Style grey.png'),
    'Puma RS-X Style white.png': require('../../assets/image/Shoes/Puma RS-X Style white.png'),
    'Puma Velocity Nitro black.png': require('../../assets/image/Shoes/Puma Velocity Nitro black.png'),
    'Puma Velocity Nitro lemon.png': require('../../assets/image/Shoes/Puma Velocity Nitro lemon.png'),
    'Reebok Classic Fit blue.png': require('../../assets/image/Shoes/Reebok Classic Fit blue.png'),
    'Reebok Classic Fit crim.png': require('../../assets/image/Shoes/Reebok Classic Fit crim.png'),
    'Reebok Floatride Energy blue.png': require('../../assets/image/Shoes/Reebok Floatride Energy blue.png'),
    'Reebok Floatride Energy white.png': require('../../assets/image/Shoes/Reebok Floatride Energy white.png'),
    'Reebok Nano X black.png': require('../../assets/image/Shoes/Reebok Nano X black.png'),
    'Reebok Nano X white.png': require('../../assets/image/Shoes/Reebok Nano X white.png'),
    'Reebok Nano X yellow.png': require('../../assets/image/Shoes/Reebok Nano X yellow.png'),
    'Reebok Runner Lite blue.png': require('../../assets/image/Shoes/Reebok Runner Lite blue.png'),
    'Reebok Runner Lite white.png': require('../../assets/image/Shoes/Reebok Runner Lite white.png'),
    'Reebok Zig Dynamica black.png': require('../../assets/image/Shoes/Reebok Zig Dynamica black.png'),
    'Reebok Zig Dynamica blue.png': require('../../assets/image/Shoes/Reebok Zig Dynamica blue.png'),
    'Reebok Zig Dynamica red.png': require('../../assets/image/Shoes/Reebok Zig Dynamica red.png'),
};

export const getShoeImage = (name?: string) => {
    if (!name) return require('../../assets/image/Shoes/Adidas Adizero Speed grey.png');
    return shoeImageMap[name] || require('../../assets/image/Shoes/Adidas Adizero Speed grey.png');
};